targets:
  $default:
    sources:
      - lib/**
      - lib/gql/schema.graphql
    builders:
      artemis:
        options:
          fragments_glob: lib/gql/fragments/**.graphql
          schema_mapping:
            - output: lib/gql/generated/graphql_api.dart
              schema: lib/gql/schema.graphql
              queries_glob: lib/gql/operations/**.graphql
          scalar_mapping:
            - custom_parser_import: 'package:graph/gql/coercers.dart'
              graphql_type: Time
              dart_type: DateTime
            - graphql_type: ID
              dart_type: int