name: graph
description: A new Flutter project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  artemis: ^7.0.0-beta.13
  blocitory:
    path: ../../../../../_apps/blocitory
#    git:
#      url: git@github.com:kateile/blocitory.git
#      ref: main #You need to force the update with flutter packages upgrade
  dio: ^4.0.2
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  equatable: ^2.0.3
  fluro: ^2.0.3
  flutter_phoenix: ^1.0.0
  flutter_secure_storage: ^5.0.2
  gql: 0.13.1-alpha+1645425888336
  gql_dio_link: ^0.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  in_app_update: ^3.0.0
  path_provider: ^2.0.6
  permission_handler: ^9.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.mahesabu.graph
        pluginClass: GraphPlugin
      ios:
        pluginClass: GraphPlugin
      linux:
        pluginClass: GraphPlugin
      macos:
        pluginClass: GraphPlugin
      windows:
        pluginClass: GraphPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
