on:
  push:
    branches:
      - internal #What developers see
      - alpha #
      - beta #
      - production #What our users use
      - main
name: "Build & Release"
jobs:
  generate:
    name: Generate codes
    runs-on: windows-10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: run msix build script
        shell: pwsh
        run: .\client/scripts/build_offline_msi.ps1

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "client/apps/offline/build/windows/runner/Release/client.msix"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
