name: client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  server:
    path: ../../packages/server
  graph:
    path: ../../packages/graph

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  msix: ^3.6.2

flutter:
  uses-material-design: true

msix_config:
  display_name: Sokonfity
  publisher_display_name: Sylivanus Kateile
  identity_name: sokonify.offline.app
  msix_version: 1.0.0.0
  #logo_path: C:\path\to\logo.png
  capabilities: internetClient, location, webcam
  enable_at_startup: true