on:
  push:
    branches:
      - production

name: "Build & Release Windows app"
jobs:
  generate:
    name: Build Windows app
    runs-on: windows-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: kateile/blocitory
          token: ${{ secrets.BROCITORY_ACCESS_TOKEN }}
          path: blocitory
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: run msix build script
        shell: pwsh
        working-directory: client/scripts
        run: ./build_offline_msi.ps1

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "client/apps/offline/build/windows/runner/Release/client.msix"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
